#reference
#dateformat uses moment.js


backend:
  name: git-gateway
  branch: master # Branch to update (master by default). It will use the publish command to push to this branch
  squash_merges: true

display_url: https://www.sheldonhull.com
media_folder: "assets/img" # Folder where user uploaded files should go
logo_url: images/content/sheldon_400x400.jpg
editor:
    preview: false
publish_mode: editorial_workflow
collections: # A list of collections the CMS should be able to edit
  - name: "microblog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "micro.blog" # Used in the UI, ie.: "New Post"
    folder: "content/microblog" # The path to the folder where the documents are stored
    format: yaml-frontmatter
    extension: md
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}"
    identifier_field: title
    fields: # The fields each document in this collection have
      # MAIN AUTHORING AREA
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", required: true}
      - {label: "title", name: "title", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["tech","til"]
        options: ["til","development","sql-server","tech","ramblings",powershell,"cool-tools","performance-tuning","deep-dive","AWS","devops","redgate","tfs","photography","music","follower-of-Jesus","worship","videography","azure"]
        multiple: true
        required: true
        allow_add: true
    # - label: "Post Author"
    #   name: "author"
    #   widget: "relation"
    #   collection: "authors"
    #   searchFields: ["name", "twitterHandle"]
    #   valueField: "name"
    #   displayFields: ["twitterHandle", "followerCount"]
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "blog" # Used in the UI, ie.: "New Post"
    folder: "content/blog" # The path to the folder where the documents are stored
    format: yaml-frontmatter
    extension: md
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    #identifier_field: slug
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "slug", name: "slug", widget: "string", tagname: "h1", required: true}
      # MAIN AUTHORING AREA
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Last Modified Date", name: "last_modified_at", widget: "date", format: "YYYY-MM-DD",required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
        # Additional string fields to set manually in YAML
      - {label: "toc", name: "toc", widget: "boolean", default: true}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: true}
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
      - label: "Tags"
        name: "tags"
        widget: "select"
        default: "tech"
        options: ["til","development","sql-server","tech","ramblings",powershell,"cool-tools","performance-tuning","deep-dive","AWS","devops","redgate","tfs","photography","music","follower-of-Jesus","worship","videography","azure"]
        multiple: true
        required: true
        allow_add: true
      - {label: "typora-root-url", name: "typora-root-url", widget: "hidden", default: "..\\static\\images", required: true, hint: "Use ..\\static\\images"}
      - {label: "typora-copy-images-to", name: "typora-copy-images-to", widget: "hidden", default: "..\\static\\images", required: true, hint: "Use ..\\static\\images"}
  - name: "docs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "docs" # Used in the UI, ie.: "New Post"
    folder: "content/docs" # The path to the folder where the documents are stored
    format: yaml-frontmatter
    extension: md
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    #identifier_field: slug
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "slug", name: "slug", widget: "string", tagname: "h1", required: true}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Last Modified Date", name: "last_modified_at", widget: "date", format: "YYYY-MM-DD",required: true}
      # MAIN AUTHORING AREA
      - {label: "Body", name: "body", widget: "markdown", required: true}

        # Additional string fields to set manually in YAML
      - {label: "toc", name: "toc", widget: "boolean", default: true}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: true}
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
      - label: "Tags"
        name: "tags"
        widget: "select"
        default: "tech"
        options: ["til","development","sql-server","tech","ramblings",powershell,"cool-tools","performance-tuning","deep-dive","AWS","devops","redgate","tfs","photography","music","follower-of-Jesus","worship","videography","azure"]
        multiple: true
        required: true
        allow_add: true
      - {label: "typora-root-url", name: "typora-root-url", widget: "hidden", default: "..\\static\\images", required: true, hint: "Use ..\\static\\images"}
      - {label: "typora-copy-images-to", name: "typora-copy-images-to", widget: "hidden", default: "..\\static\\images", required: true, hint: "Use ..\\static\\images"}
