---
baseurl: "" #https://www.sheldonhull.com
title: "sheldonhull.com"
theme: "hermit"
languageCode: "en-us"
defaultContentLanguage: "en"
metadataformat: "yaml"

enableGitInfo: true

paginate: 20
canonifyurls: true
pluralizeListTitles: false
rssLimit: 10  # Maximum number of items in the RSS feed.

pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsUseClasses: true

enableEmoji: true  # Shorth and emojis in content files - https://gohugo.io/functions/emojify/

# Analytics & Comments
disqusShortname: "sheldonhull"
googleAnalytics: "UA-40198001-3"


copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true
  nofollowLinks: true


taxonomies:
  tag: "tags"
  # Categories are disabled by default.

outputs:
  home: ["HTML", "RSS"]
  page: ["HTML"]

permalinks:
  posts: "/blog/:title/"
Author:
  name: "Sheldon Hull"
  website: "https://www.sheldonhull.com"
  email: ""
  facebook: ""
  googleplus: "" # or xxxxxxxxxxxxxxxxxxxxx
  github: "sheldonhull"
  gitlab: ""
  bitbucket: ""
  twitter: "sheldon_hull"
  reddit: ""
  linkedin: ""
  xing: ""
  stackoverflow: "users/68698/sheldonh"
  snapchat: ""
  instagram: ""
  youtube: "" # or channel/channelname
  soundcloud: ""
  spotify: ""
  bandcamp: ""
  itchio: ""
  vk: ""
  paypal: ""
  telegram: ""
  500px: ""
menu:
  main:
    - name: "Blog"
      weight: 1
      url : "/blog/"
    - name: "Tags"
      url: "/tags/"
      weight: 2
    - name: "Docs"
      url: "/docs/"
      weight: 3
    - name: "About"
      weight: 4
      url: "/about/"

params:
  dateform       : "Jan 2, 2006"
  dateformShort  : "Jan 2"
  dateformNum    : "2006-01-02"
  dateformNumTime: "2006-01-02 15:04 -0700"


  # Metadata mostly used in document's head
  themeColor: "#22252e" # "#494f5c"


  homeSubtitle: "DevOps // SQL & Automation"
  footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  bgImg: "images/2016-04-27_17-27-07_circular.jpg"  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl: "https://github.com/sheldonhull/sheldonhull.hugo/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent: false  # Set "text-align: justify" to `.content`.

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.

  # SHELDON: My addition
  commit: true
  since: "2013"

  # Add custom css
  custom_css: ["css/custom.css","css/ticks.css","css/notice.css"]

  social:
    - name: "twitter"
      url: "https://twitter.com/sheldon_hull"
    - name: "github"
      url: "https://github.com/sheldonhull"

  style:
    backgroundColor: "#018574"