#baseurl = "https://www.sheldonhull.com"
title = "sheldonhull.com"
#theme = "hermit"

# Themes
#theme = "sam"
#theme = "hermit"
theme = "beautifulhugo"
#theme = "hugo-material-docs"
#theme = "hugo-coder"
#theme = "cupper-hugo-theme"
#theme = "hugo-theme-casper"

#languagecode = "en"
# for hermit languageCode = "en-us"
languageCode = "en-us"
defaultContentLanguage = "en"
#defaultcontentlanguage = "en"
metadataformat = "yaml"

paginate = 20
canonifyurls = true
rssLimit = 10  # Maximum number of items in the RSS feed.

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true
pluralizeListTitles = false


# Analytics & Comments
disqusShortname = ""
googleAnalytics = ""


# # START HERMIT
# [taxonomies]
#   tag = "tags"
#   # Categories are disabled by default.

# [params]
#   avatarurl = "/images/sheldon_120x120.jpg"


#   dateform        = "Jan 2, 2006"
#   dateformShort   = "Jan 2"
#   dateformNum     = "2006-01-02"
#   dateformNumTime = "2006-01-02 15:04 -0700"

#   # Metadata mostly used in document's head
#   # description = ""
#   # images = [""]
#   themeColor = "#494f5c"
# # START HERMIT

[permalinks]
posts = "/blog/:title/"



[menu]
    # Menu links
    [[menu.main]]
        name = "Blog"
        weight = 1
        url  = "/blog/"
    [[menu.main]]
        name = "About"
        weight = 4
        url = "/about/"
    [[menu.main]]
        name = "docs"
        identifier="docs"
        #url = "/docs/"
        weight = 4

    [[menu.main]]
        name = "Tags"
        url = "/tags/"
        weight = 2

[[menu.main]]
   parent = "docs"
   name = "awspowershell"
   url = "docs/awspowershell"
   weight = 3

[[menu.main]]
   parent = "docs"
   name = "dbatools"
   url = "docs/dbatools"
   weight = 2

[[menu.main]]
   parent = "docs"
   name = "powershell"
   url = "docs/powershell"
   weight = 1
