---
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - ':speech_balloon: blog comment'
# Label to use when marking an issue as stale
staleLabel: no-recent-activity
# Comment to post when marking an issue as stale. Set to `false` to disable
# No comment as I use this to power github utterance comments. No need to comment on close.
markComment: false
# >
#   This issue has been automatically marked as stale because it has not had
#   recent activity. It will be closed if no further activity occurs. Thank you
  # for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
