---
# IF ERROR ON INSTALL:
# brew uninstall pre-commit
# install with non-admin install this works on mac
# curl https://pre-commit.com/install-local.py | python -

# Setup: pre-commit install
# Upgrade: pre-commit autoupdate
# Run: pre-commit run --all-files
# https://pre-commit.com/hooks.html
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
exclude: (.terraform.lock.hcl)|(.devcontainer/)|(.cache/)|(.vscode/)

repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    # https://github.com/jumanjihouse/pre-commit-hook-yamlfmt#override-defaults
    # https://yaml.readthedocs.io/en/latest/example.html
    rev: 0.1.0 # or specific tag
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1 # or higher tag
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # Use the ref you want to point at
    # Documentation on the arguments for these hooks https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        exclude: ^.vscode/
        args: [--autofix, --no-ensure-ascii]

      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: forbid-new-submodules
      - id: name-tests-test
      - id: sort-simple-yaml
        # - id: no-commit-to-branch
        # args: [--branch, develop, --branch, master, --branch, main]
      - id: requirements-txt-fixer
      - id: check-toml
  # https://pre-commit.com/#supported-languages
  - repo: local
    hooks:
      # FIRST TIME SETUP:  GO111MODULE=on go get github.com/zricethezav/gitleaks/v4@latest
      # - id: local-run
      #   name: Scan for secrets
      #   entry: gitleaks --pretty -v
      #   language: system
      - id: gitleaks
        name: gitleaks-scan
        entry: zsh -c docker run -v ${PWD}:/repo zricethezav/gitleaks:latest --path="/repo" --pretty -v
        language: system
      - id: markdownlint
        name: markdownlint-autofix
        entry: zsh -c docker run -i --rm -v ${PWD}:/work tmknom/markdownlint:latest --fix --config ./settings/.markdownlint.yaml content/docs
        language: system
      - id: shellcheck
        name: shellcheck
        entry: zsh -c docker run --rm -v "${PWD}:/mnt" koalaman/shellcheck:stable --format=json
        language: system
  - repo: https://github.com/tchoedak/pre-commit-sql-format
    rev: v0.0.1
    hooks:
      - id: format-sql
