# IF ERROR ON INSTALL:
# brew uninstall pre-commit
# install with non-admin install this works on mac
# curl https://pre-commit.com/install-local.py | python -

# Setup: pre-commit install
# Upgrade: pre-commit autoupdate
# Run: pre-commit run --all-files
# https://pre-commit.com/hooks.html
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: pretty-format-json
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker

# https://pre-commit.com/#supported-languages
-   repo: local
    hooks:
    # FIRST TIME SETUP:  GO111MODULE=on go get github.com/zricethezav/gitleaks/v4@latest
    -   id: local-run
        name: Scan for secrets
        entry: gitleaks --pretty -v
        language: system
        #entry: bash -c gitleaks
        #entry: docker run --rm -v pwd:/code/ zricethezav/gitleaks -v --repo-path=/code/gitleaks
        # docker_image: zricethezav/gitleaks:latest
        # language: docker_image
        # entry: zricethezav/gitleaks:latest -v
