baseurl = "https://www.sheldonhull.com"
title = "sheldonhull.com"

# Themes
#theme = "sam"
#theme = "hermit"
#theme = "beautifulhugo"
#theme = "hugo-material-docs"
theme = "hugo-coder"
#theme = "cupper-hugo-theme"
#theme = "hugo-theme-casper"

#languagecode = "en"
# for hermit languageCode = "en-us"
languageCode = "en-us"
defaultContentLanguage = "en"
#defaultcontentlanguage = "en"
metadataformat = "yaml"

paginate = 20
canonifyurls = true


pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

pluralizeListTitles = false


# Analytics & Comments
disqusShortname = ""
googleAnalytics = ""



# START HERMIT
[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  avatarurl = "/images/sheldon_120x120.jpg"


  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"
# START HERMIT

[permalinks]
posts = "/blog/:title/"

#Beautiful hugo// others that support commit hash
#Prior to running hugo, run this   GIT_COMMIT_SHA=`git rev-parse --verify HEAD` GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
[Params]
  commit = "https://github.com/sheldonhull/sheldonhull.hugo/master/"
  custom_css = ["css/style.css"]

# [menu]
# [[menu.nav]]
# name = "Home"
# url = "/"
# weight = 1
# [[menu.nav]]
# name = "Blog"
# url = "/blog/"
# weight = 2
# [[menu.nav]]
# name = "Tags"
# url = "/tags/"
# weight = 3
# [[menu.nav]]
# name = "Docs"
# url = "/docs/"
# weight = 4
# [[menu.nav]]
# name = "About"
# url = "/about/"
# weight = 5
# [[menu.nav]]
# name = "RSS"
# url = "/index.xml"
# weight = 6

# # for hermit

# [menu]

#   [[menu.main]]
#     name = "blog"
#     url = "blog/"
#     weight = 10

#   [[menu.main]]
#     name = "About"
#     url = "about/"
#     weight = 20



[menu]
    # for themes that only have main nav
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/blog/"
  [[menu.main]]
  name = "Tags"
  weight = 1
  url  = "/tags/"
[[menu.main]]
  name = "Docs"
  weight = 1
  url  = "/docs/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about/"
# [[menu.main]]
#   name = "Home"
#   weight = 1
#   url  = "/"