baseurl: ''
title: Sheldon Hull
theme: hermit
metadataformat: yaml
timeout: 60000
enableGitInfo: true
paginate: 20
canonifyurls: true
pluralizeListTitles: false
enableEmoji: true
DisqusShortname: sheldonhull
DelayDisqus: true
googleAnalytics: UA-40198001-3
copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License.
additional_scripts:
  - node_modules/algoliasearch/dist/algoliasearch.umd.js
  - assets/js/algolia-search.js
taxonomies:
  tag: tags
  series: series
outputs:
  home:
    - HTML
    - RSS
    - Algolia
  page:
    - HTML
  section:
    - HTML
    - RSS
  microblog:
    - RSS
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
permalinks:
  posts: /:slug/
frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - :git
    - lastmod
    - date
    - publishDate
    - :fileModTime
  publishDate:
    - publishDate
    - date
  expiryDate:
    - expiryDate
  title:
    - title
    - date
Author:
  name: Sheldon Hull
  website: https://www.sheldonhull.com
  email: ''
  facebook: ''
  googleplus: ''
  github: sheldonhull
  gitlab: ''
  bitbucket: ''
  twitter: sheldon_hull
  reddit: ''
  linkedin: ''
  xing: ''
  stackoverflow: users/68698/sheldonh
  snapchat: ''
  instagram: ''
  youtube: ''
  soundcloud: ''
  spotify: ''
  bandcamp: ''
  itchio: ''
  vk: ''
  paypal: ''
  telegram: ''
  500px: ''
menu:
  main:
    - name: Blog
      weight: 1
      url: /blog/
    - name: 100 Days Of Code
      weight: 1
      url: https://100-days-of-code-sheldonhull.netlify.app/
    - name: Microblog
      weight: 1
      url: /microblog/
    - name: Tags
      url: /tags/
      weight: 2
    - name: Docs
      url: /docs/
      weight: 3
    - name: Creative
      url: /creative/
      weight: 4
    - name: About
      weight: 5
      url: /about/
params:
  mainSections:
    - blog
  search:
    algolia:
      app_id: 04HSGXXQD5
      api_key: a7ec2763a5d966a5b9f8d70b254bfb68
      index_name: sheldonhull
      show_logo: true
  RSSSection:
    - blog
  rssmicroblogtitles: true
  RSSEnabled: true
  rssLimit: 15
  font:
    text: Raleway
    code: JetBrainsMono
  dateform: Jan 2, 2006
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04 -0700
  comments: true
  toc: true
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
    params:
      - tags
  themeColor: '#22252e'
  homeSubtitle:
    - "Developer & Reticulator Of Splines"
    - "For dropping by, here's some emoji tacos :taco: :taco: :taco:"
  footerCopyright: '&#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  bgImg: images/2016-04-27_17-27-07_circular.jpg
  gitUrl: https://github.com/sheldonhull/sheldonhull.hugo/commit/
  justifyContent: false
  commit: true
  since: 2013
  custom_css:
    - css/custom.css
    - css/ticks.css
    - css/notice.css
  social:
    - name: twitter
      url: https://twitter.com/sheldon_hull
    - name: github
      url: https://github.com/sheldonhull
    - name: stackoverflow
      url: https://stackoverflow.com/users/68698/sheldonh
    - name: linkedin
      url: https://www.linkedin.com/in/sheldonhull
  style:
    backgroundColor: '#018574'
markup:
  blackFriday:
    angledQuotes: false
    extensions: null
    extensionsMask: null
    footnoteAnchorPrefix: ''
    footnoteReturnLinkContents: ''
    fractions: true
    hrefTargetBlank: true
    latexDashes: true
    nofollowLinks: false
    noreferrerLinks: false
    plainIDAnchors: true
    skipHTML: false
    smartDashes: true
    smartypants: true
    smartypantsQuotesNBSP: false
    taskLists: true
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xHTML: false
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  minify:
    disableCSS: false
    disableHTML: false
    disableJS: false
    disableJSON: false
    disableSVG: false
    disableXML: false
    minifyOutput: false
    tdewolff:
      css:
        decimals: -1
        keepCSS2: true
      html:
        keepConditionalComments: true
        keepDefaultAttrVals: true
        keepDocumentTags: true
        keepEndTags: true
        keepQuotes: false
        keepWhitespace: false
      js: {}
      json: {}
      svg:
        decimals: -1
      xml:
        keepWhitespace: false
