baseurl = "https://www.sheldonhull.com"
title = "sheldonhull.com"

# Themes
#theme = "sam"
theme = "hugo-material-docs"
#theme = "hugo-coder"
#theme = "cupper-hugo-theme"
#theme = "hugo-theme-casper"

languagecode = "en"
defaultcontentlanguage = "en"
metadataformat = "yaml"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

pluralizeListTitles = false
avatarurl = "images/sheldon_120x120.jpg"

# Analytics & Comments
disqusShortname = ""
googleAnalytics = ""


[permalinks]
posts = "/blog/:title/"



[menu]
[[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.nav]]
  name = "Blog"
  url = "/blog/"
  weight = 2
[[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 3
  [[menu.nav]]
  name = "Docs"
  url = "/docs/"
  weight = 4
[[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 5
[[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 6


# for themes that only have main nav
[[menu.main]]
  name = "Home"
  weight = 1
  url  = "/"
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/blog/"
  [[menu.main]]
  name = "Tags"
  weight = 1
  url  = "/tags/"
[[menu.main]]
  name = "Docs"
  weight = 1
  url  = "/docs/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about/"