baseURL: 'https://www.sheldonhull.com'
defaultContentLanguage: en
# theme: ["hugo-debugprint","codeit"]
# themesDir: ../..
title: sheldonhull.com
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
ignoreErrors:
  - error-remote-getjson
languages:
  en:
    weight: 1
    languageCode: en
    languageName: English
    hasCJKLanguage: false
    paginate: 12
    googleAnalytics: UA-40198001-3
    copyright: >-
      This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    menu:
      main:
        - identifier: posts
          pre: ''
          post: ''
          name: posts
          url: /posts
          title: ''
          weight: 1
        - identifier: about
          pre: ''
          post: ''
          name: about
          url: /about/
          title: ''
          weight: 3
        - identifier: docs
          pre: ''
          post: ''
          name: docs
          url: /docs/
          title: ''
          weight: 4
        - identifier: creative
          pre: ''
          post: ''
          name: creative
          url: /creative/
          title: ''
          weight: 5
        - identifier: tags
          pre: ''
          post: ''
          name: tags
          url: /tags/
          title: ''
          weight: 6
        - identifier: github
          pre: <i class='fab fa-github fa-fw'></i>
          post: ''
          name: ''
          url: 'https://github.com/sheldonhull/'
          title: GitHub
          weight: 7
    params:
      description: A personal dev blog
      keywords:
        - Theme
        - Hugo
      app:
        title: sheldonhull.com
        noFavicon: false
        svgFavicon: ''
        themeColor: '#ffffff'
        iconColor: '#5bbad5'
        tileColor: '#da532c'
      search:
        enable: true
        type: algolia
        contentLength: 4000
        placeholder: ''
        maxResultLength: 10
        snippetLength: 30
        highlightTag: em
        absoluteURL: https://www.sheldonhull.com
        algolia:
          index: sheldonhull.com
          appID: 04HSGXXQD5
          searchKey: a7ec2763a5d966a5b9f8d70b254bfb68
      home:
        rss: 15
        profile:
          enable: true
          gravatarEmail: ''
          avatarURL: /images/sheldonhull_gopher_avatar.png
          title: 'Sheldon Hull'
          subtitle: ''
          typeit: true
          social: true
          disclaimer: ''
        posts:
          enable: true
          paginate: 6
      social:
        GitHub: sheldonhull
        Linkedin: ''
        Twitter: sheldon_hull
        Instagram: ''
        Facebook: ''
        Telegram: ''
        Medium: ''
        Gitlab: ''
        Youtubelegacy: ''
        Youtubecustom: ''
        Youtubechannel: ''
        Tumblr: ''
        Quora: ''
        Keybase: ''
        Pinterest: ''
        Reddit: ''
        Codepen: ''
        FreeCodeCamp: ''
        Bitbucket: ''
        Stackoverflow: users/68698/sheldonh
        Weibo: ''
        Odnoklassniki: ''
        VK: ''
        Flickr: ''
        Xing: ''
        Snapchat: ''
        Soundcloud: ''
        Spotify: ''
        Bandcamp: ''
        Paypal: ''
        Fivehundredpx: ''
        Mix: ''
        Goodreads: ''
        Lastfm: ''
        Foursquare: ''
        Hackernews: ''
        Kickstarter: ''
        Patreon: ''
        Steam: ''
        Twitch: ''
        Strava: ''
        Skype: ''
        Whatsapp: ''
        Zhihu: ''
        Douban: ''
        Angellist: ''
        Slidershare: ''
        Jsfiddle: ''
        Deviantart: ''
        Behance: ''
        Dribbble: ''
        Wordpress: ''
        Vine: ''
        Googlescholar: ''
        Researchgate: ''
        Thingiverse: ''
        Devto: sheldonhull
        Gitea: ''
        XMPP: ''
        Matrix: ''
        Bilibili: ''
        Email:
        RSS: true
        #Mastodon:
        #  id: '@xxxx'
        #  prefix: 'https://mastodon.technology/'

params:
  debug: false
  mainSections:
      - posts
  version: 0.2.X
  defaultTheme: dark
  gitRepo: https://github.com/sheldonhull/sheldonhull.hugo
  fingerprint: ''
  dateFormat: 2006-01-02
  images:
    - /images/sheldonhull_gopher_avatar.png
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: /images/sheldonhull_gopher_avatar.png
      name: sheldonhull.com
      #pre: '<i class="fas fa-terminal"></i>'  #<i class='fas fa-laptop-code fa-fw'></i>
      pre: <span id="logo-anima"><span class="arrow">></span><span class="dash">_</span></span>
      post: ''
      typeit: false
  footer:
    enable: true
    custom: ''
    hugo: true
    copyright: true
    author: true
    since: 2013
    icp: ''
    license: >-
      <a rel="license external nofollow noopener noreferrer"
      href="https://www.sheldonhull.com/main/license" target="_blank">CC
      BY-NC 4.0</a>
  section:
    paginate: 20
    dateFormat: 2006-01-02
    rss: 10
  list:
    paginate: 20
    dateFormat: 2006-01-02
    rss: 10
  page:
    hiddenFromHomePage: false
    hiddenFromSearch: false
    twemoji: false
    lightgallery: true
    ruby: true
    fraction: true
    fontawesome: true
    linkToMarkdown: true
    rssFullText: true
    toc:
      enable: true
      keepStatic: false
      auto: false
    code:
      copy: true
      maxShownLines: 20
    math:
      enable: false
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      copyTex: true
      mhchem: true
    mapbox:
      accessToken: ''
      lightStyle: 'mapbox://styles/mapbox/light-v10?optimize=true'
      darkStyle: 'mapbox://styles/mapbox/dark-v10?optimize=true'
      navigation: true
      geolocate: true
      scale: true
      fullscreen: true
    share:
      enable: true
      Twitter: true
      Facebook: false
      Linkedin: true
      Whatsapp: false
      Pinterest: false
      Tumblr: false
      HackerNews: false
      Reddit: false
      VK: false
      Buffer: false
      Xing: false
      Line: false
      Instapaper: false
      Pocket: false
      Digg: false
      Stumbleupon: false
      Flipboard: false
      Weibo: false
      Renren: false
      Myspace: false
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Mix: false
    comment:
      enable: true
      disqus:
        enable: false
        shortname: ''
      gitalk:
        enable: false
        owner: ''
        repo: ''
        clientId: ''
        clientSecret: ''
      valine:
        enable: false
        appId: ''
        appKey: ''
        placeholder: ''
        avatar: mp
        meta: ''
        pageSize: 10
        lang: ''
        visitor: true
        recordIP: true
        highlight: true
        enableQQ: false
        serverURLs: ''
        emoji: ''
      facebook:
        enable: false
        width: 100%
        numPosts: 10
        appId: ''
        languageCode: ''
      telegram:
        enable: false
        siteID: ''
        limit: 5
        height: ''
        color: ''
        colorful: true
        dislikes: false
        outlined: false
      commento:
        enable: false
      utterances:
        enable: true
        repo: 'sheldonhull/sheldonhull.hugo'
        issueTerm: 'title'
        label: ':speech_balloon: blog comment'
        lightTheme: github-light
        darkTheme: github-dark
    library:
      css:
        - https://fonts.googleapis.com/css?family=Raleway&display=swap
      js:
        - <script src="/javascript/webmentions.js" async></script>
        - <script src="/javascript/app.js" async></script>
        - <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/2.3.1/list.min.js"></script>
    seo:
      images: []
      publisher:
        name: xxxx
        logoUrl: images/sheldonhull_gopher_avatar.png
  typeit:
    speed: 100
    cursorSpeed: 1000
    cursorChar: '|'
    duration: -1
  verification:
    google: ''
    bing: ''
    yandex: ''
    pinterest: ''
    baidu: ''
  seo:
    image: /images/sheldonhull_gopher_avatar.png
    thumbnailUrl: /images/sheldonhull_gopher_avatar.png
  analytics:
    enable: true
    google:
      id: UA-40198001-3
      anonymizeIP: true
    fathom:
      id: ''
      server: ''
    plausible:
      domain: ''
  cookieconsent:
    enable: false
    content:
      message: ''
      dismiss: ''
      link: ''
  cdn:
    data: jsdelivr.yml
  compatibility:
    polyfill: false
    objectFit: false
markup:

  # From Hugo Docs: https://xyproto.github.io/splash/docs/
  # Using https://pygments.org/docs/styles/ supported and converted into the hugo highlighter chroma https://pygments.org/demo/
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: default
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
author:
  name: Sheldon Hull
  email: ''
  link: ''
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: :slug
  /: :slug
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - Algolia
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML

taxonomies:
  tag: tags
  series: series

RSSSection:
- posts

module:
  imports:
      # Debug Helper for Layouts: https://github.com/kaushalmodi/hugo-debugprint
    - path: github.com/dnb-hugo/debugprint
      # github.com/kaushalmodi/hugo-debugprint
      # github.com/dnb-hugo/debugprint
      # ignoreConfig: true
      # ignoreImports: true
      disable: false
    - path: github.com/sunt-programator/CodeIT
      disable: false
