version: "3.7"
# docker volume create hugo_caddy_data
# docker compose -f "docker-compose.caddy.yml" up --build -d
# docker compose  -f "docker-compose.caddy.yml" down --volumes --remove-orphans
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "3100:3100"
      # - "443:443"
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      - ${PWD}/_static:/_site
      - hugo_caddy_data:/data
      - caddy_config:/config
volumes:
  hugo_caddy_data:
    external: true
  caddy_config:
