#
#
# HUGO_VERSION=0.84 && docker-compose -f "docker-compose.hugo.yml" down --remove-orphans --volumes && docker-compose -f "docker-compose.hugo.yml" build --build-arg HUGO_VERSION=$HUGO_VERSION && docker-compose -f "docker-compose.hugo.yml" up
#
#
version: '3'
services:
  hugo_server:
    # HUGO_VERSION: 0.xx
    build:
      context: .
      dockerfile: Dockerfile.hugo
      args:
        - HUGO_VERSION=0.87
    environment:
      - HUGO_ENABLEGITINFO=0
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
