###############################
# PUBLISH/PUBLIC
###############################
[build]
  #command = "git status --porcelain &&  git submodule update --init --recursive && GIT_COMMIT_SHA='git rev-parse --verify HEAD' && GIT_COMMIT_SHA_SHORT='git rev-parse --short HEAD' && hugo"
  command = """
echo "DEPLOY_PRIME_URL = $DEPLOY_PRIME_URL"
# HUGO_BASEURL=$DEPLOY_PRIME_URL #not setting, as no branch naming for production deploy
echo "HUGO_BASEURL = $HUGO_BASEURL"

echo `hugo version`
git status --porcelain
git submodule update --init --recursive
export GIT_COMMIT_SHA=`git rev-parse --verify HEAD`
export GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
echo "GIT_COMMIT_SHA       = $GIT_COMMIT_SHA"
echo "GIT_COMMIT_SHA_SHORT = $GIT_COMMIT_SHA_SHORT"
hugo --verbose --verboseLog --minify --destination $HUGO_DESTINATION
""" # -b $DEPLOY_PRIME_URL
  publish = "public"



[build.environment]
  HUGO_ENABLEGITINFO = "true"
  HUGO_BASEURL = "https://www.sheldonhull.com/"
  HUGO_MINIFY = "true"
  HUGO_DESTINATION = "public"
  HUGO_VERSION = "0.59.0"


###############################
# DEPLOY PREVIEWS
###############################
[context.deploy-preview]
  command = """
echo "DEPLOY_PRIME_URL = $DEPLOY_PRIME_URL"
HUGO_BASEURL=$DEPLOY_PRIME_URL
echo "HUGO_BASEURL = $HUGO_BASEURL"
hugo version
git status --porcelain
git submodule update --init --recursive
export GIT_COMMIT_SHA=`git rev-parse --verify HEAD`
export GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
echo "GIT_COMMIT_SHA       = $GIT_COMMIT_SHA"
echo "GIT_COMMIT_SHA_SHORT = $GIT_COMMIT_SHA_SHORT"
hugo --buildFuture --verbose --minify --gc --destination $HUGO_DESTINATION
"""
publish = "preview"

[context.deploy-preview.environment]
  HUGO_GOOGLEANALYTICS = "dev"
  HUGO_BASEURL = "$DEPLOY_PRIME_URL"
  HUGO_ENABLEGITINFO = "true"
  HUGO_DESTINATION = "preview"
  HUGO_VERSION = "0.59.0"
###############################
# BRANCH
###############################
[context.branch-deploy]
  publish = "branch"
  command = """
echo "DEPLOY_PRIME_URL = $DEPLOY_PRIME_URL"
HUGO_BASEURL=$DEPLOY_PRIME_URL
echo "HUGO_BASEURL = $HUGO_BASEURL"

hugo version
git status --porcelain
git submodule update --init --recursive
export GIT_COMMIT_SHA=`git rev-parse --verify HEAD`
export GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
echo "GIT_COMMIT_SHA       = $GIT_COMMIT_SHA"
echo "GIT_COMMIT_SHA_SHORT = $GIT_COMMIT_SHA_SHORT"
hugo --buildFuture --buildDrafts --verbose --minify --gc --destination $HUGO_DESTINATION
"""
[context.branch-deploy.environment]
  HUGO_GOOGLEANALYTICS = "dev"
  HUGO_BASEURL = "$DEPLOY_PRIME_URL"
  HUGO_ENABLEGITINFO = "true"
  HUGO_DESTINATION = "branch"
  HUGO_VERSION = "0.59.0"
# Redirects to keep jekyll based urls that some use like:
#xmlUrl="https://www.sheldonhull.com/tags/tech/feed.xml"  should still be working, since hugo generates with index.xml

[[redirects]]
  from = "/feed.xml"
  to = "/index.xml"
  status = 200
  force = true
[[redirects]]
  from = "/feed/"
  to = "/index.xml"
  status = 200
  force = true
[[redirects]]
  from = "/feed"
  to = "/index.xml"
  status = 200
  force = true
[[redirects]]
  from = "*/feed.xml"
  to = "/index.xml"
  status = 200
  force = true