---
# demo https://github.com/go-task/examples/blob/master/go-web-app/Taskfile.yml

version: '3'
output: prefixed
silent: true
env:
  HUGO: hugo
  DEFAULT_BUILD_SERVER: http://127.0.0.1:1313 #localhost:1313
  DEFAULT_HUGO_DESTINATION: _site
  HUGO_VERSION: 0.80.0
  GITHUB_REPO: github.com/sheldonhull/sheldonhull.hugo
  DOCKER_BUILDKIT: 1
  # AWS_SDK_LOAD_CONFIG: 1
  # AWS_REGION:  # Override for local developement work
vars:
  DATA_DIR: ./data
  WEBMENTION_FILE: webmentions.json
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  TODAY: '{{now | date "2006-01-02"}}' # https://golang.org/src/time/format.go
  YEAR: '{{now | date "2006"}}' # https://golang.org/src/time/format.go
  MONTH: '{{now | date "01"}}' # https://golang.org/src/time/format.go
  DAY: '{{now | date "02"}}' # https://golang.org/src/time/format.go
  # HUGO DESIRED OUTPUT: 2021-05-24T17:55:12-05:00
  TODAY_UTC: '{{ now | date "2006-01-02T15:04:05-07:00" }}' # Example Output 2021-05-24T17:55:12-05:00
  black: \033[:0;30m
  red: \033[:0;31m
  green: \033[:0;32m
  orange: \033[:0;33m
  blue: \033[:0;34m
  purple: \033[:0;35m
  cyan: \033[:0;36m
  light_gray: \033[:0;37m
  dark_gray: \033[:1;30m
  light_red: \033[:1;31m
  light_green: \033[:1;32m
  yellow: \033[:1;33m
  light_blue: \033[:1;34m
  light_purple: \033[:1;35m
  light_cyan: \033[:1;36m
  white: \033[:1;37m
  nocolor: \u001b[0m
  reversed: \u001b[7m
  CODE_CONFIG: .code-config

tasks:
  default:
    cmds:
      - task: list
  list:
    desc: list tasks
    cmds:
      - task --list
  vars:
    desc: variable output
    cmds:
      - |
        echo -e "{{.light_gray}}=== ℹ {{ .reversed }} Variable Info from Task {{ .nocolor }} === "
        echo -e "{{.light_gray}}TODAY                {{.nocolor}}: {{ .orange}}{{ .TODAY }} {{ .nocolor }}"
        echo -e "{{.light_gray}}TODAY_UTC            {{.nocolor}}: {{ .orange}}{{ .TODAY_UTC }} {{ .nocolor }}"
        echo -e "{{.light_gray}}GIT_COMMIT           {{.nocolor}}: {{ .orange}}{{ .GIT_COMMIT }} {{ .nocolor }}"
        echo -e "{{.light_gray}}WEBMENTION_IO_TOKEN  {{.nocolor}}: {{ .orange}}{{ if empty .WEBMENTION_IO_TOKEN }}💥 not set{{end}}{{else}}✅ token detected{{end}} {{ .nocolor }}"

  serve:
    desc: Build and run hugo
    cmds:
      - |
        if [ -x "$(command -v gp)" ]; then
          echo "gitpod command: $(gp url 1313)"
          export DEPLOY_PRIME_URL=$(gp url 1313)
        fi
      - $HUGO serve -b ${DEPLOY_PRIME_URL:-$DEFAULT_BUILD_SERVER} --verbose --enableGitInfo -d _site --buildFuture --buildDrafts --gc # --disableFastRender

      # - task: build
  echo-debug:
    desc: output variables for debugging netlify or other build tasks
    cmds:
      - echo "$(hugo version)"
      - git status --porcelain
      - |
        if [ -x "$(command -v gp)" ]; then
          echo "gitpod command: $(gp url 1313)"
          export DEPLOY_PRIME_URL=$(gp url 1313)
        fi
      - echo "DEPLOY_PRIME_URL   = $DEPLOY_PRIME_URL"
      - echo "HUGO_BASEURL = $HUGO_BASEURL"
      - export GIT_COMMIT_SHA=`git rev-parse --verify HEAD`
      - export GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
      - echo "GIT_COMMIT_SHA       = $GIT_COMMIT_SHA"
      - echo "GIT_COMMIT_SHA_SHORT = $GIT_COMMIT_SHA_SHORT"
      - echo "HUGO_GOOGLEANALYTICS  = $HUGO_GOOGLEANALYTICS"
      - echo "HUGO_ENABLEGITINFO    = $HUGO_ENABLEGITINFO"
      - echo "HUGO_VERSION          = $HUGO_VERSION"
  build:
    desc: Build the webpage for previews or other debug setup
    #deps: [assets, templates]
    cmds:
      - $HUGO --buildFuture --buildDrafts --enableGitInfo --verbose --minify --gc --destination ${HUGO_DESTINATION:-$DEFAULT_HUGO_DESTINATION} -b ${DEPLOY_PRIME_URL:-$DEFAULT_BUILD_SERVER}
  build-public:
    desc: Build algolia public json only if missing algolia
    generates:
      - public/algolia.json
    env:
      HUGO_ENABLEGITINFO: 'true'
      HUGO_BASEURL: https://www.sheldonhull.com/
      HUGO_MINIFY: 'true'
      HUGO_DESTINATION: public
      #ALGOLIA_ADMIN_KEY: SET IN LOCAL ENVIRONMENT ONLY
      # DEPLOY_PRIME_URL:
      #-b $DEPLOY_PRIME_URL
    cmds:
      - $HUGO --enableGitInfo  --gc --cleanDestinationDir --verboseLog --minify --destination ${HUGO_DESTINATION:-$DEFAULT_HUGO_DESTINATION} -b ${DEPLOY_PRIME_URL:-$DEFAULT_BUILD_SERVER}
  init:
    desc: Initialize project to ensure dependencies, submodules, and tooling is ready
    cmds:
      # - git submodule update --init --recursive
      # - git rm ./themes/codeit
      - hugo mod get
      # -    {{ .GITHUB_REPO }}
      # - hugo mod get -u -v
      # - hugo mod tidy
      - npm install --quiet atomic-algolia #--globals
      - |
        {{ if eq OS "windows" }}scoop install sed{{end}}
  go:
    desc: Setup go environment
    cmds:
      - go get github.com/algolia/algoliasearch-client-go/v3@v3.4.0
      - go get -u
  go-run:
    desc: Try running the new go algolia command
    cmds:
      - go run main.go
  algolia:
    desc: Generate algolia json
    # deps: [build-public]
    # These are configured in the .devcontainer but no harm in setting here too
    env:
      ALGOLIA_APP_ID: 04HSGXXQD5
      ALGOLIA_INDEX_FILE: public/algolia.json
      ALGOLIA_INDEX_NAME: sheldonhull.com
    cmds:
      - npm run algolia
  theme-update:
    desc: rebase on remote theme to pull in the upstream changes
    cmds:
      # - git submodule update --rebase --remote
      - hugo mod get -u
  deinit_submodule:
    desc: cleanup submodule
    cmds:
      - |
        git submodule deinit themes/codeit
        git rm themes/codeit
        rm -rf .git/modules/themes/codeit
        git rm --cached themes/codeit
  blog:
    desc: Create a new blog post
    cmds:
      - |
        echo -e "{{.light_gray}}=== ℹ {{ .reversed }} Variable Info from Task {{ .nocolor }} === "
        echo -e "{{.light_gray}}TODAY_UTC                {{.nocolor}}: {{ .orange}}{{ .TODAY_UTC }} {{ .nocolor }}"
        echo -e "{{.green}}Please enter title{{ .nocolor }}"
        read;
        echo -e "{{.green}}Title: ${REPLY}{{ .nocolor }}"
        title=$(echo ${REPLY} \
          | sed 's/\(.\)\([A-Z]\)/\1-\2/g' \
          | sed 's/[[:space:]]*//g' \
          | sed -e 's/\(.*\)/\L\1/'

        )
        #tr '[:upper:]' '[:lower:]'
        directory="./content/blog/"
        mkdir -p $directory/{{ .YEAR }} || echo -e "{{.dark_gray}}🔄 skipped creation of directory [$directory] per already exists {{.nocolor}}"
        filename=$directory/{{ .YEAR }}/{{ .YEAR }}-{{ .MONTH }}-{{ .DAY }}-$title.md
        echo -e "{{ .dark_gray }} creating new file: $filename {{ .nocolor }}"
        hugo new $filename --kind blog
        echo -e "{{ .green }} ✅ created: $filename {{ .nocolor }}"
  100daysofcode_readconfig:
    desc: read the counter values for 100 days of code to simplify creation from archetype
    cmds:
      - |
        source {{ .CODE_CONFIG }}
        echo -e "{{.light_gray}}=== ℹ {{ .reversed }} 100 Days Of Code Config from: [{{ .CODE_CONFIG}}] {{ .nocolor }} === "
        echo -e "{{.light_gray}}LANGUAGE                {{.nocolor}}: {{ .orange}} $LANGUAGE {{ .nocolor }}"
        echo -e "{{.light_gray}}ROUND                   {{.nocolor}}: {{ .orange}} $ROUND {{ .nocolor }}"
        echo -e "{{.light_gray}}COUNTER                 {{.nocolor}}: {{ .orange}} $COUNTER {{ .nocolor }}"
  post:
    desc: Create a new post
    cmds:
      - task: 100daysofcode_readconfig
      - |
        echo -e "{{.light_gray}}=== ℹ {{ .reversed }} Variable Info from Task {{ .nocolor }} === "
        echo -e "{{.light_gray}}TODAY_UTC {{.nocolor}}: {{ .orange}}{{ .TODAY_UTC }} {{ .nocolor }}"
        echo -e "{{.green}}Please enter title{{ .nocolor }}"
        read;
        echo -e "{{.green}}Title: ${REPLY}{{ .nocolor }}"
        title=$(echo ${REPLY} \
          | sed 's/\(.\)\([A-Z]\)/\1-\2/g' \
          | sed 's/[[:space:]]*//g' \
          | sed -e 's/\(.*\)/\L\1/'
        )
        ##| tr '[:upper:]' '[:lower:]'
        echo -e "{{.green}}Please enter [blog, microblog, code] for archetype{{ .nocolor }}"
        read;
        archetype=$(echo ${REPLY})

        #directory="./content/posts/"
        mkdir -p "./content/posts/{{ .YEAR }}" &>/dev/null || echo -e "{{.dark_gray}}🔄 skipped creation of directory [$directory] per already exists {{.nocolor}}"
        filename="./content/posts/{{ .YEAR }}/{{ .YEAR }}-{{ .MONTH }}-{{ .DAY }}-$title.md"
        echo -e "{{.dark_gray}}default filename: [$filename]{{ .nocolor }}"
        if [[ $archetype == "code" ]];
        then
          # source {{ .CODE_CONFIG }}
          echo -e "{{.light_gray}}=== ℹ {{ .reversed }} 100 Days Of Code Config from: [{{ .CODE_CONFIG}}] {{ .nocolor }} ==="
          echo -e "{{.light_gray}}LANGUAGE                {{.nocolor}}: {{ .orange}} $LANGUAGE {{ .nocolor }}"
          echo -e "{{.light_gray}}ROUND                   {{.nocolor}}: {{ .orange}} $ROUND {{ .nocolor }}"
          echo -e "{{.light_gray}}COUNTER                 {{.nocolor}}: {{ .orange}} $COUNTER {{ .nocolor }}"

          UPDATED_COUNTER=$(($COUNTER+1))
          TARGET_KEY=COUNTER
          REPLACEMENT_VALUE=$UPDATED_COUNTER
          echo -e "ℹ️ {{.dark_gray}} \"s/\($TARGET_KEY *= *\).*/\1$REPLACEMENT_VALUE/g\" \"{{ .CODE_CONFIG }}\"{{ .nocolor }}"

          sed -i '' "s/\($TARGET_KEY *= *\).*/\1$REPLACEMENT_VALUE/g" "{{ .CODE_CONFIG }}"

          echo -e "{{.green}} 💾 updated code config with new counter: from [$COUNTER] to [$UPDATED_COUNTER] (saved in {{ .CODE_CONFIG }}){{ .nocolor }}"
          echo -e "{{.dark_gray}} ℹ override filename with 100days of code naming convention{{ .nocolor }}"

          filename=./content/posts/{{ .YEAR }}/{{ .YEAR }}-{{ .MONTH }}-{{ .DAY }}-$LANGUAGE-R$ROUND-day-$UPDATED_COUNTER.md
          hugo new $filename --kind $archetype

          # Replace the counter in the text file
          sed -i '' "s/VAR_LANGUAGE/$LANGUAGE/g" "$filename"
          sed -i '' "s/VAR_ROUND/$ROUND/g" "$filename"
          sed -i '' "s/VAR_DAYCOUNTER/$UPDATED_COUNTER/g" "$filename"
          echo -e "{{.dark_gray}} 💾 update VAR_DAYCOUNTER,VAR_LANGUAGE,VAR_DAY_COUNTER in output file{{ .nocolor }}"
        else
          hugo new $filename --kind $archetype
        fi
        echo -e "{{ .dark_gray }} creating new file: $filename {{ .nocolor }}"
        echo -e "{{ .green }} ✅ created [ $archetype ] at: [ $filename ] {{ .nocolor }}"
  bear:
    desc: Run bhugo to sync posts
    cmds:
      - |
        echo -e "{{.light_gray}}=== ℹ {{ .reversed }} Running Bear Hugo {{ .nocolor }} === "
        go get -u github.com/Zach-Johnson/bhugo
        bhugo
    preconditions:
      - test -f .bhugo
# TODO: Add task for imageoptim preprocessing on staged files only
  install-tools:
    desc: Install extra build tools that aren't needed as part of a CICD normally
    cmds:
      - |
        # HOMEBREW_FORCE_BREWED_CURL=1
        # {{if eq OS "darwin"}}
        # brew install node || brew upgrade node
        # rm -rf /usr/local/lib/node_modules
        # brew uninstall node
        # brew install node --without-npm
        # echo prefix=~/.npm-packages >> ~/.npmrc
        # curl -L https://www.npmjs.com/install.sh | sh
        #npm update npm -g
        #export PATH="$HOME/.npm-packages/bin:$PATH"


        # {{else}}
        # echo "Need command added for non-darwin system
        # {{end}}
      - |
        # brew reinstall node
        npm install imageoptim-cli --global --silent
        npm install markdownlint-cli2 --global --silent

        # npm install -g install netlify-cli --silent
        {{ if eq OS "windows" }}scoop install jq jid{{end}}
        {{ if eq OS "darwin" }}brew install jq jid{{end}}
      - |
        GO111MODULE=off go get -u -v github.com/sheldonhull/sharedbrain
        echo -e "{{ .green }} ✅ sharedbrain installed{{ .nocolor }}"
      - go install github.com/owenrumney/squealer/cmd/squealer@latest
      - go install github.com/evilmartians/lefthook@master
      - lefthook install --aggressive
  webmentions:
    desc: Generate local datafile of webmentions
    cmds:
      - |
        go get -v github.com/nekr0z/webmention.io-backup@master
        mkdir {{ .DATA_DIR }} || echo -e "{{ .dark_gray}}created DATA_DIR: {{ .DATA_DIR }}{{.nocolor}}"
        pushd {{ .DATA_DIR }}
        $(go env GOPATH)/bin/webmention.io-backup -f "{{ .WEBMENTION_FILE }}" -t "{{ .WEBMENTION_IO_TOKEN }}"
        echo -e "{{ .green }} ✅ results persisted to: {{ .WEBMENTION_FILE }}{{ .nocolor }}"
        jq "." {{ .WEBMENTION_FILE }} > tmp.json
        cat tmp.json > {{ .WEBMENTION_FILE }}
        rm tmp.json
        popd
  sharedbrain:
    desc: use shared brain tool to generate markdown links from wiki links
    cmds:
      - |
        #echo $(go env GOPATH)
        #go get -u github.com/sheldonhull/sharedbrain@main
        #export
        #GO111MODULE=off go install github.com/sheldonhull/sharedbrain #@main
        # GO111MODULE=off go get -u -v github.com/sheldonhull/sharedbrain
        sharedbrain -content ./content/posts  -dest ./content/posts
