backend:
  name: git-gateway
  branch: master # Branch to update (master by default). It will use the publish command to push to this branch
  squash_merges: true

display_url: https://www.sheldonhull.com
media_folder: "assets/img" # Folder where user uploaded files should go
logo_url: https://d33wubrfki0l68.cloudfront.net/21446a9fe6768fbc72d304626343179b74759ac8/95052/assets/img/sheldon_400x400.jpg

publish_mode: editorial_workflow
collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    format: yaml-frontmatter
    extension: md
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      # MAIN AUTHORING AREA
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Last Modified Date", name: "last_modified_at", widget: "date", format: "YYYY-MM-DD",required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
        # Additional string fields to set manually in YAML
      - {label: "toc", name: "toc", widget: "boolean", default: true}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: true}
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
      - label: "Tags"
        name: "tags"
        widget: "select"
        default: "tech"
        options: ["development","sql-server","tech","ramblings",powershell,"cool-tools","performance-tuning","deep-dive","AWS","devops","redgate","tfs","photography","music","follower-of-Jesus","worship","videography","azure"]
        multiple: true
        required: true
        allow_add: true
      - {label: "typora-root-url", name: "typora-root-url", widget: "hidden", default: "..\\assets\\img", required: true, hint: "Use ..\\assets\\img"}
      - {label: "typora-copy-images-to", name: "typora-copy-images-to", widget: "hidden", default: "..\\assets\\img", required: true, hint: "Use ..\\assets\\img"}
  - name: "docs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "docs" # Used in the UI, ie.: "New Post"
    folder: "_docs" # The path to the folder where the documents are stored
    format: yaml-frontmatter
    extension: md
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Last Modified Date", name: "last_modified_at", widget: "date", format: "YYYY-MM-DD",required: true}
      # MAIN AUTHORING AREA
      - {label: "Body", name: "body", widget: "markdown", required: true}


        # Additional string fields to set manually in YAML
      - {label: "toc", name: "toc", widget: "boolean", default: true}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: true}
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
      - {label: "permalink", name: "permalink", widget: "string", required: true, default: "/docs/{{title}}/"}
      - label: "Tags"
        name: "tags"
        widget: "select"
        default: "tech"
        options: ["development","sql-server","tech","ramblings",powershell,"cool-tools","performance-tuning","deep-dive","AWS","devops","redgate","tfs","photography","music","follower-of-Jesus","worship","videography","azure"]
        multiple: true
        required: true
        allow_add: true
      - {label: "typora-root-url", name: "typora-root-url", widget: "hidden", default: "..\\assets\\img", required: true, hint: "Use ..\\assets\\img"}
      - {label: "typora-copy-images-to", name: "typora-copy-images-to", widget: "hidden", default: "..\\assets\\img", required: true, hint: "Use ..\\assets\\img"}
  - name: "portfolio" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Portfolio" # Used in the UI, ie.: "New Post"
    folder: "_portfolio" # The path to the folder where the documents are stored
    format: yaml-frontmatter
    extension: md
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD", required: true}
      - {label: "Last Modified Date", name: "last_modified_at", widget: "date", format: "YYYY-MM-DD",required: true}

      # MAIN AUTHORING AREA
      - {label: "Body", name: "body", widget: "markdown", required: true}

      - {label: "toc", name: "toc", widget: "boolean", default: true}
      - {label: "permalink", name: "permalink", widget: "string", required: true, default: "/{{title}}/"}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: true}
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
      - label: "Tags"
        name: "tags"
        widget: "select"
        default: "tech"
        options: ["development","sql-server","tech","ramblings",powershell,"cool-tools","performance-tuning","deep-dive","AWS","devops","redgate","tfs","photography","music","follower-of-Jesus","worship","videography","azure"]
        multiple: true
        required: true
        allow_add: true
      - {label: "typora-root-url", name: "typora-root-url", widget: "hidden", default: "..\\assets\\img", required: true, hint: "Use ..\\assets\\img"}
      - {label: "typora-copy-images-to", name: "typora-copy-images-to", widget: "hidden", default: "..\\assets\\img", required: true, hint: "Use ..\\assets\\img"}
