---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/microblog
  label: microblog
  create: documents
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  exclude: blog/*
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
upload_dir: static/images
public_path: images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -enableGitinfo -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  output_directory: public
  instant_preview_command: 'hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public -enableGitinfo '
version: 0.54.0
