baseurl = "http://www.example.com"
title = "johndoe"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = ""

#Beautiful hugo// others that support commit hash
#Prior to running hugo, run this   GIT_COMMIT_SHA=`git rev-parse --verify HEAD` GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
[Params]
  commit = "https://github.com/sheldonhull/sheldonhull.hugo/master/"
  inverted = true
  hideCredits = true
  hideCopyright = true
  rtl = false

  # Series see also post count
  maxSeeAlsoItems = 5

  # Custom CSS
  custom_css = ["css/custom.css","css/ticks.css","css/notice.css"]

[taxonomies]
  series = "series"
  tag = "tags"



[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/sheldonhull/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/sheldon.hull/"
[menu]
    # for themes that only have main nav
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/blog/"
  [[menu.main]]
  name = "Tags"
  weight = 1
  url  = "/tags/"
[[menu.main]]
  name = "Docs"
  weight = 1
  url  = "/docs/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about/"
# [[menu.main]]
#   name = "Home"
#   weight = 1
#   url  = "/"