FROM jekyll/builder:latest

# Adds a C compiler and make, and the headers for ruby
RUN apk --update add alpine-sdk ruby-dev
#RUN apk --update add dos2unix

# Add extra: jekyll-responsive_images, which requires imagemagick-dev
#RUN apk --update add imagemagick

# fix line ending issues
#RUN apk --update add dos2unix
#RUN dos2unix /entrypoint.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*
ADD Gemfile .

# installs to system location
RUN gem install bundler && bundle install --system
#RUN gem install bundler && bundle install --path # now cache gems to a location of my choosing

RUN apk --update add dumb-init
#RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64
#RUN chmod +x /usr/local/bin/dumb-init
# ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
#WORKDIR /site
#COPY entrypoint.sh /entrypoint.sh

RUN jekyll -v
EXPOSE 4000

#ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
RUN bundle install
RUN bundle update
RUN bundle exec jekyll build
CMD jekyll serve -h 0.0.0.0 -P 4000 --config _config.yml,_config.dev.yml --verbose --trace
#bundle exec
ENV JEKYLL_ENV docker



#  CHECK PERMISSIONS
# PS> docker run --rm --volume="$PWD":/srv/jekyll -it -p 4000:4000 jekyll/builder:latest jekyll serve --force_polling --host 0.0.0.0