---
label: blog-post
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: list
  name: tags
  label: tags
- type: text
  name: title
  label: title
- type: text
  name: slug
  label: slug
