---
label: blog-post
hide_body: false
fields:
- type: datetime
  name: date
  label: date
  config:
    date_format: YYYY-MM-DD
    time_format: HH:mm:ssZ
    required: true
  default: now
- type: text
  name: title
  label: title
  config:
    required: true
- type: text
  name: slug
  label: slug
  config:
    required: true
- name: excerpt
  type: text
  config:
    required: true
  label: excerpt
- type: list
  name: tags
  label: tags
pages:
- content/blog/the-importance-of-good-acceptance-criteria-leveraging-gherkin.md
- content/blog/generating-diagrams-programmatically.md
- content/blog/terraform-for-dummies.md
- content/blog/infrastructure-as-code.md
