---
label: microblog
hide_body: false
fields:
- type: datetime
  name: title
  label: title
  hidden: true
  config:
    display_utc: true
    required: true
    time_format: hh:mm:ssZ
    date_format: YYYY/MM/DD
  default: now
  description: microblog uses date as the title
- type: datetime
  name: date
  label: date
  hidden: false
  config:
    display_utc: true
    required: true
    date_format: YYYY/MM/DD
    time_format: hh:mm:ssZ
  default: now
- type: list
  name: tags
  label: tags
  config:
    use_select: true
    source:
      type: simple
      section: ''
      path: ''
    options:
    - til
    - tech
- name: body
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
  label: body
