---
label: microblog
hide_body: false
fields:
- type: datetime
  name: title
  label: title
  hidden: false
  config:
    display_utc: false
    required: true
    time_format: HH:mm:ssZ
    date_format: YYYY-MM-DD
  default: now
  description: microblog uses date as the title
- type: datetime
  name: date
  label: date
  hidden: false
  config:
    display_utc: false
    required: true
    date_format: YYYY-MM-DD
    time_format: HH:mm:ssZ
  default: now
- type: list
  name: tags
  label: tags
  config:
    use_select: false
    source:
      type: simple
      section: ''
      path: ''
    options:
    - til
    - tech
pages:
- content/microblog/2019-05-16t11-15-28-05-00.md
- content/microblog/2019-05-17t15-57-32-05-00.md
- content/microblog/2019-05-17t15-59-50-05-00.md
- content/microblog/2019-05-31t14-00-42-05-00.md
- content/microblog/2019-04-25t00-39-35-05-00.md
- content/microblog/2019-04-20t03-48-12-00-00.md
