---
name: Atomic Algolia Update

on:
  push:
    branches:
      - master
jobs:
  build_hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      - run: npm install atomic-algolia
      # - name: Installing Homebrew
      #   run: |
      #     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      #     test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
      #     test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
      #     echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
      #     echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >>~/.bashrc
      #     echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >>~/.profile
      #     source ~/.bashrc
      #     source ~/.profile
      #     brew --version
      # - name: Verify Homebrew's Installation
      #   run: |
      #     cat ~/.profile
      #     echo "======================="
      #     cat ~/.bashrc
      #     echo "======================="
      #     brew --version
      # # - run: |
      # #     sudo apt install linuxbrew-wrapper
      # #     # mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
      # - run: brew install hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.69.0
          extended: true

      - name: Build Hugo Site And Algolia Json
        run: hugo --minify --enableGitInfo -d _site --disableKinds ["RSS","HTML"]

      - run: npm run algolia
        env:
          ALGOLIA_APP_ID: 04HSGXXQD5
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: sheldonhull
          ALGOLIA_INDEX_FILE: _site/algolia.json
