jekyll:
  image: jekyll/jekyll:latest
  container_name: sheldonhull.github.io
  command: >-
     bundle exec jekyll serve --port 4000 --config _config.yml,_config.dev.yml --force_polling --incremental
  ports:
    - '4000:4000'
  environment:
    - JEKYLL_ENV=production
    - DOCKER_API_VERSION=1.24
    - COMPOSE_API_VERSION=1.24
  volumes:
    - '.:/srv/jekyll'
#jekyll s --port 4000 --config _config.yml,_config.dev.yml --force_polling --incremental