---
name: Trigger Issue Labeling
on:
  issue_comment:
  workflow_dispatch:
jobs:
  build:
    name: Trigger Issue Labeling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: damccorm/tag-ur-it@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issue-rules.yml
