name: Atomic Algolia Update

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APP_ID=04HSGXXQD5
      ALGOLIA_ADMIN_KEY={{ `secrets.ALGOLIA_ADMIN_KEY` }}
      ALGOLIA_INDEX_NAME=sheldonhull
      ALGOLIA_INDEX_FILE=_site/algolia.json
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 7.6
        uses: actions/setup-node@v1
        with:
          node-version: 7.6
      - run: npm install atomic-algolia
      - uses: jakejarvis/hugo-build-action@master
        with:
          args: '--minify --enableGitInfo -d _site --gc'
      - run: npm run algolia
