---
# .github/workflows/main.yaml
name: Trigger Netlify Build
on:
  schedule:
    # https://crontab.guru/#0_7_*_*_1,3,5
    # At 07:00 on Monday, Wednesday, and Friday.
    - cron: 0 7 * * 1,3,5
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${NETLIFY_BUILD_HOOK}
    env:
      NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
